- name: Provision base image
  hosts: default

  pre_tasks:
    - name: Update system repository
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install git
      apt:
        name: git
        state: present

  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    # Enable IPv4 traffic forwarding in order to use Docker 
    sysctl_config:
      net.ipv4.ip_forward: 1
    ssh_permit_root_login: 'yes'
