- name: Provision base image
  hosts: all

  pre_tasks:
    - name: Shutdown if not Ubuntu system
      command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "Ubuntu"

    - name: Update system repository
      apt:
        update_cache: yes
        upgrade: dist

  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Configure OS hardening
      import_role:
        name: devsec.hardening.os_hardening

    - name: Configure SSH hardening
      import_role:
        name: devsec.hardening.ssh_hardening
      vars:
        ssh_permit_root_login: 'yes'

    - name: Configure Java on the system
      import_role:
        name: geerlingguy.java

    - name: Configure Nginx
      import_tasks: nginx.yml
      tags:
        - nginx

    - name: Include Jenkins tasks 
      import_tasks: jenkins.yml
