name: Check project files
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Validate packer
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          target: packer/os-base-snapshot.json

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check terraform
        continue-on-error: false

      - name: Terraform init
        id: init
        run: terraform init terraform

      - name: Terraform validate
        id: validate
        run: terraform validate terraform
